name: Build Develop Push
on:
  push:
    branches:
      - 'feature/build-ci'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  develop
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.DNX_AK }}
          password: ${{ secrets.DNX_SK }} 
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}
          no-cache: true
          build-args: |
            RAPIDPRO_APPS_GIT_URL=https://github.com/Ilhasoft/rapidpro-apps.git
            RAPIDPRO_APPS_GIT_BRANCH=main
            PROTOBUFFERS_URL=https://github.com/Ilhasoft/weni-protobuffers.git
      - name: Build and push - Varnish Image
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile.varnish
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}-varnish
          no-cache: true
          build-args: |
            BACKEND_ADDRESS=push-develop:8000
