name: Build staging push
on:
  push:
    tags:
      - 'staging-v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  staging
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 242357350604.dkr.ecr.sa-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          file: ./Dockerfile
          push: true
          tags: 242357350604.dkr.ecr.sa-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}
          no-cache: true
          build-args: |
            RAPIDPRO_APPS_GIT_URL='https://github.com/Ilhasoft/rapidpro-apps.git'
            RAPIDPRO_APPS_GIT_BRANCH='main'
            PROTOBUFFERS_URL='https://github.com/Ilhasoft/weni-protobuffers.git'
      - name: Build and push - Rapidpro Image
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          file: ./Dockerfile.varnish
          push: true
          tags: 242357350604.dkr.ecr.sa-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}
          no-cache: true
          build-args: |
            BACKEND_ADDRESS='push-stagin:8000'
